services:
  - type: web
    name: mern-blog-api
    env: node
    buildCommand: npm install
    startCommand: pm2 start server.js --name blog-api
    envVars:
      - key: MONGO_URI
        value: <your-mongodb-uri>
      - key: JWT_SECRET
        value: <your-secret-key>
